!SESSION 2021-03-16 14:09:49.614 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.arm.ds.default
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.default

This is a continuation of log file C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\.metadata\.bak_0.log
Created Time: 2021-03-19 14:44:53.892

!ENTRY com.arm.newsfeed 4 0 2021-03-19 14:44:54.015
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-19 16:44:53.590
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-19 18:44:54.100
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-19 20:44:53.712
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-19 22:44:53.675
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-20 00:44:54.015
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-20 04:22:46.011
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-20 06:27:53.335
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-20 10:27:47.815
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 10:40:54.840
!MESSAGE Variable references non-existent resource : ${workspace_loc:/MyCPEN391Project/Debug/MyCPEN391Project.axf}
!STACK 1
org.eclipse.core.runtime.CoreException: Variable references non-existent resource : ${workspace_loc:/MyCPEN391Project/Debug/MyCPEN391Project.axf}
	at org.eclipse.debug.internal.core.variables.WorkspaceResolver.resolveValue(WorkspaceResolver.java:56)
	at org.eclipse.core.internal.variables.DynamicVariable.getValue(DynamicVariable.java:55)
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.resolve(StringSubstitutionEngine.java:270)
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.substitute(StringSubstitutionEngine.java:195)
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.performStringSubstitution(StringSubstitutionEngine.java:87)
	at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:574)
	at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:350)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.resolveVariables(VariableResolvingLaunchConfiguration.java:297)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.getAttribute(VariableResolvingLaunchConfiguration.java:146)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.getAttribute(VariableResolvingLaunchConfiguration.java:145)
	at com.arm.debugger.launcher2.debugresources.ResourceLaunchConfigHelper.loadResourcesFromConfig(ResourceLaunchConfigHelper.java:29)
	at com.arm.debugger.control.ConnectionPropertiesBuilder.setTCFDownloadDirectories(ConnectionPropertiesBuilder.java:290)
	at com.arm.debugger.control.ConnectionPropertiesBuilder.parseProperties(ConnectionPropertiesBuilder.java:217)
	at com.arm.debugger.control.ConnectionController.doPreDebugServiceInitialization(ConnectionController.java:651)
	at com.arm.debugger.control.ConnectionController.doInitialize(ConnectionController.java:555)
	at com.arm.debugger.control.ConnectionController.manageThreadModelAndInitialize(ConnectionController.java:539)
	at com.arm.debugger.control.ConnectionController.manageProgressResourceAndInitialize(ConnectionController.java:484)
	at com.arm.debugger.control.ConnectionController.initialize(ConnectionController.java:432)
	at com.arm.debugger.control.ConnectionManager.createConnection(ConnectionManager.java:360)
	at com.arm.debugger.launcher.TargetLauncher.launch(TargetLauncher.java:20)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.launch(VariableResolvingLaunchConfiguration.java:273)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
!SUBENTRY 1 org.eclipse.core.resources 4 368 2021-03-20 10:40:54.899
!MESSAGE Variable references non-existent resource : ${workspace_loc:/MyCPEN391Project/Debug/MyCPEN391Project.axf}

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 10:44:37.468
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-292
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 11:32:46.868
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-306
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 11:50:06.998
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.GeneratedMethodAccessor430.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-306
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.newsfeed 4 0 2021-03-20 12:27:48.505
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-20 14:27:47.516
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 16:01:28.028
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-378
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.newsfeed 4 0 2021-03-20 16:28:01.627
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 16:40:45.424
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-390
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 17:09:00.405
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-398
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 17:18:54.767
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread Worker-397
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-20 17:34:15.278
!MESSAGE Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
!STACK 0
com.arm.debug.interpreter.ds.DSException: Image "C:\Users\zoeyli\cpen391\CPEN391_group25\DS-5 Workspace\MyCPEN391Project\Debug\MyCPEN391Project.axf" does not exist
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:37)
	at com.arm.debug.interpreter.ds.commands.file.ReloadSymbolFileCommand.execute(ReloadSymbolFileCommand.java:1)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:414)
	at com.arm.debug.interpreter.ds.DSInterpreter$3.run(DSInterpreter.java:1)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$QueuedTask.run(ConnectionEventManager.java:102)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processTask(ConnectionEventManager.java:314)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$8(ConnectionEventManager.java:312)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:217)
	at com.arm.debugger.control.CommandTask.fillInStackTrace(CommandTask.java:53)
	at com.arm.debugger.control.ConnectionController.execute(ConnectionController.java:1247)
	at com.arm.debugger.api.AbstractCommands.execute(AbstractCommands.java:114)
	at com.arm.debugger.api.Commands.reloadSymbolFile(Commands.java:410)
	at com.arm.debugger.control.ConnectionController.observeEvent(ConnectionController.java:1725)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.arm.debugger.control.PriorityEventSender.fireEvents(PriorityEventSender.java:379)
	at com.arm.debugger.control.PriorityEventSender.queueEvent(PriorityEventSender.java:287)
	at com.arm.debugger.control.PriorityEventSender.observeEvent(PriorityEventSender.java:226)
	at com.arm.debugger.control.ConnectionEventManager$1.observeEvent(ConnectionEventManager.java:80)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.processEvent(ConnectionEventManager.java:377)
	at com.arm.debug.core.engine.connection.ConnectionEventManager.access$7(ConnectionEventManager.java:320)
	at com.arm.debug.core.engine.connection.ConnectionEventManager$2.run(ConnectionEventManager.java:215)
Asynchronously called from thread MainThread
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.proxy.DebugServiceWrapper.invoke(DebugServiceWrapper.java:78)
	at com.sun.proxy.$Proxy26.reloadSymbolsFile(Unknown Source)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:26)
	at com.arm.debugger.api.commands.ReloadSymbolFile.execute(ReloadSymbolFile.java:1)
	at com.arm.debugger.api.AbstractDebugCommand.call(AbstractDebugCommand.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.arm.debugger.control.CommandTask.run(CommandTask.java:45)
	at com.arm.debugger.control.ConnectionController$5.run(ConnectionController.java:1388)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.newsfeed 4 0 2021-03-20 18:28:01.851
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-20 23:18:38.984
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-21 04:57:17.860
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-21 09:07:24.045
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-21 14:27:07.092
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-21 16:27:07.050
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-21 18:27:08.184
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-21 20:27:07.466
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-21 22:27:07.269
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 00:27:07.585
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 02:27:07.406
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 04:27:07.427
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 06:27:07.824
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 08:27:07.280
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 10:27:07.272
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 12:27:07.197
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 14:27:07.587
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 16:58:07.636
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 18:58:23.484
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 20:58:07.295
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-22 23:46:14.845
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-23 01:56:10.824
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-23 04:01:11.711
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-23 06:06:15.559
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-23 13:05:04.687
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
java.net.UnknownHostException: community.arm.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:174)
	at com.sun.syndication.io.XmlReader.<init>(XmlReader.java:151)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)

!ENTRY com.arm.newsfeed 4 0 2021-03-23 15:05:04.616
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-23 17:05:04.697
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-23 19:05:04.689
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.newsfeed 4 0 2021-03-23 21:05:04.924
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more
!SESSION 2021-03-24 13:33:51.750 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.arm.ds.default
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.default

!ENTRY org.eclipse.core.resources 2 10035 2021-03-24 13:34:04.749
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY com.arm.newsfeed 4 0 2021-03-24 13:34:27.811
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY org.eclipse.cdt.core 1 0 2021-03-24 13:44:28.523
!MESSAGE Indexed 'cpen391_integrate' (0 sources, 0 headers) in 0.02 sec: 0 declarations; 0 references; 0 unresolved inclusions; 0 syntax errors; 0 unresolved names (0.00%)
!SESSION 2021-03-24 13:50:06.526 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.arm.ds.default
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.default

!ENTRY org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for ALT+CTRL+I:
Binding(ALT+CTRL+I,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.include.browser,Open Include Browser,
		Open an include browser on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6e7a1662,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(ALT+CTRL+I,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.include.browser,Open Include Browser,
		Open an include browser on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6e7a1662,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for ALT+SHIFT+R:
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.text.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.cdt.ui.category.refactoring,Refactor - C++,C/C++ Refactorings,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1153b498,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.text.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.cdt.ui.category.refactoring,Refactor - C++,C/C++ Refactorings,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1153b498,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@e75700b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for F3:
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.opendecl,Open Declaration,
		Open an editor on the selected element's declaration(s),
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@400ee997,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.opendecl,Open Declaration,
		Open an editor on the selected element's declaration(s),
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@400ee997,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(F3,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.open.editor,Open Declaration,
		Open an editor on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1309d95c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.navigate.opentype,Open Element,
		Open an element in an Editor,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6b9d30c7,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.navigate.opentype,Open Element,
		Open an element in an Editor,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6b9d30c7,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1ced9003,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for F4:
Binding(F4,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.type.hierarchy,Open Type Hierarchy,
		Open a type hierarchy on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3089c3cb,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(F4,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.type.hierarchy,Open Type Hierarchy,
		Open a type hierarchy on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3089c3cb,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(F4,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.open.type.hierarchy,Open Type Hierarchy,
		Open a type hierarchy on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@24955d52,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.287
!MESSAGE A conflict occurred for CTRL+G:
Binding(CTRL+G,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.search.finddecl,Declaration,
		Search for declarations of the selected element in the workspace,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4a21c541,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(CTRL+G,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.search.finddecl,Declaration,
		Search for declarations of the selected element in the workspace,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4a21c541,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(CTRL+G,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace,Declaration in Workspace,
		Search for declarations of the selected element in the workspace,
		Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6f1d546c,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.289
!MESSAGE A conflict occurred for CTRL+SHIFT+G:
Binding(CTRL+SHIFT+G,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.search.findrefs,References,
		Search for references to the selected element in the workspace,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6e91b771,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(CTRL+SHIFT+G,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.search.findrefs,References,
		Search for references to the selected element in the workspace,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6e91b771,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(CTRL+SHIFT+G,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.search.references.in.workspace,References in Workspace,
		Search for references to the selected element in the workspace,
		Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@20a2946d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.289
!MESSAGE A conflict occurred for ALT+CTRL+H:
Binding(ALT+CTRL+H,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.call.hierarchy,Open Call Hierarchy,
		Open the call hierarchy for the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@11be90d8,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(ALT+CTRL+H,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.open.call.hierarchy,Open Call Hierarchy,
		Open the call hierarchy for the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@11be90d8,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(ALT+CTRL+H,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.open.call.hierarchy,Open Call Hierarchy,
		Open a call hierarchy on the selected element,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@76175e01,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 13:51:52.289
!MESSAGE A conflict occurred for CTRL+SHIFT+H:
Binding(CTRL+SHIFT+H,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.navigate.open.type.in.hierarchy,Open Type in Hierarchy,
		Open a type in the type hierarchy view,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@781cd038,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(CTRL+SHIFT+H,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.navigate.open.type.in.hierarchy,Open Type in Hierarchy,
		Open a type in the type hierarchy view,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@781cd038,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cViewScope,,,system)
Binding(CTRL+SHIFT+H,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type.in.hierarchy,Open Type in Hierarchy,
		Open a type in the type hierarchy view,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2baa4a23,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.cdt.core 1 0 2021-03-24 14:01:05.396
!MESSAGE Indexed 'cpen391_integrate' (0 sources, 0 headers) in 0.03 sec: 0 declarations; 0 references; 0 unresolved inclusions; 0 syntax errors; 0 unresolved names (0.00%)

!ENTRY com.arm.newsfeed 4 0 2021-03-24 15:34:28.066
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more
!SESSION 2021-03-24 18:25:57.590 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product com.arm.ds.default
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product com.arm.ds.default

!ENTRY org.eclipse.core.resources 2 10035 2021-03-24 18:26:04.339
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY com.arm.newsfeed 4 0 2021-03-24 18:26:24.832
!MESSAGE Error when reading RSS feed "http://community.arm.com/view-browse-feed.jspa?containerType=700&userID=-1&browseSite=place-content&filterID=contentstatus[published]~objecttype~objecttype[blogpost]&browseViewID=placeContent&containerID=1060"
!STACK 0
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: Content is not allowed in prolog.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:182)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:122)
	at com.arm.newsfeed.rss.AggregatedFeed.fetch(AggregatedFeed.java:226)
	at com.arm.newsfeed.rss.AggregatedFeed.access$3(AggregatedFeed.java:222)
	at com.arm.newsfeed.rss.AggregatedFeed$3.run(AggregatedFeed.java:201)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in prolog.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:178)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 6 more

!ENTRY com.arm.debugger.ux 4 0 2021-03-24 18:59:28.614
!MESSAGE Unable to connect to CPEN391_Config. The script file ( debug_server.py ) failed during execution:

Failed to launch debug server.
C:\altera\15.0\embedded\ds-5\sw\debughw\debug_server\vstrm_serverd_rddi.exe exited with error code 1

See Target Console view for more details
!STACK 0
com.arm.debugger.control.LaunchException: The script file ( debug_server.py ) failed during execution:

Failed to launch debug server.
C:\altera\15.0\embedded\ds-5\sw\debughw\debug_server\vstrm_serverd_rddi.exe exited with error code 1

See Target Console view for more details
	at com.arm.debugger.control.target.AbstractTargetController.runSetupScript(AbstractTargetController.java:187)
	at com.arm.debugger.control.target.AbstractTargetController.setupTarget(AbstractTargetController.java:87)
	at com.arm.debugger.control.ConnectionController.doPreDebugServiceInitialization(ConnectionController.java:645)
	at com.arm.debugger.control.ConnectionController.doInitialize(ConnectionController.java:555)
	at com.arm.debugger.control.ConnectionController.manageThreadModelAndInitialize(ConnectionController.java:539)
	at com.arm.debugger.control.ConnectionController.manageProgressResourceAndInitialize(ConnectionController.java:484)
	at com.arm.debugger.control.ConnectionController.initialize(ConnectionController.java:432)
	at com.arm.debugger.control.ConnectionManager.createConnection(ConnectionManager.java:360)
	at com.arm.debugger.launcher.TargetLauncher.launch(TargetLauncher.java:20)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: com.arm.debug.launch.script.ScriptException: The script file ( debug_server.py ) failed during execution:

Failed to launch debug server.
C:\altera\15.0\embedded\ds-5\sw\debughw\debug_server\vstrm_serverd_rddi.exe exited with error code 1
	at com.arm.debug.launch.script.PythonScriptRunner.run(PythonScriptRunner.java:131)
	at com.arm.debug.launch.script.TargetControlScriptRunner.run(TargetControlScriptRunner.java:36)
	at com.arm.debugger.control.target.AbstractTargetController.runSetupScript(AbstractTargetController.java:184)
	... 13 more
Caused by: Traceback (most recent call last):
  File "C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\debug_server.py", line 78, in <module>
    startDebugServer(configFile, rddidapBaseName, timeout)
  File "C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py", line 334, in startDebugServer
    launcher.launch()
  File "C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py", line 106, in launch
    serverProc = self.doLaunch()
  File "C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py", line 181, in doLaunch
    raise RuntimeError, \
RuntimeError: Failed to launch debug server.
C:\altera\15.0\embedded\ds-5\sw\debughw\debug_server\vstrm_serverd_rddi.exe exited with error code 1

	at org.python.core.PyException.doRaise(PyException.java:200)
	at org.python.core.Py.makeException(Py.java:1239)
	at org.python.core.Py.makeException(Py.java:1243)
	at rddi_dap_debug_server$py.doLaunch$13(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py:196)
	at rddi_dap_debug_server$py.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:317)
	at org.python.core.PyMethod.__call__(PyMethod.java:109)
	at rddi_dap_debug_server$py.launch$12(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py:112)
	at rddi_dap_debug_server$py.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:317)
	at org.python.core.PyMethod.__call__(PyMethod.java:109)
	at rddi_dap_debug_server$py.startDebugServer$23(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py:337)
	at rddi_dap_debug_server$py.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Scripts\rddi_dap_debug_server.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:157)
	at org.python.core.PyFunction.__call__(PyFunction.java:338)
	at org.python.pycode._pyx2.f$0(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\debug_server.py:78)
	at org.python.pycode._pyx2.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\debug_server.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1275)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
	at com.arm.debug.launch.script.PythonScriptRunner.run(PythonScriptRunner.java:120)
	... 15 more

!ENTRY com.arm.debugger.ux 4 0 2021-03-24 19:01:07.790
!MESSAGE Unable to connect to CPEN391_Config. Failed to connect to the device
Unable to connect to device Cortex-A9_0
Device already has an active connection.
!STACK 0
com.arm.debug.interpreter.ds.DSException: Failed to connect to the device
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:526)
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:513)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:295)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:1)
	at com.arm.debug.service.proxy.SingleThreader$QueuedCall.run(SingleThreader.java:61)
	at com.arm.debug.service.proxy.SingleThreader$1.run(SingleThreader.java:125)
Caused by: com.arm.debug.core.interfaces.connection.ConnectionException: Unable to connect to device Cortex-A9_0
	at com.arm.debug.targetaccess.device.TargetDevice.doConnect(TargetDevice.java:536)
	at com.arm.debug.targetaccess.device.TargetDevice.connect(TargetDevice.java:251)
	at com.arm.debug.core.engine.connection.Connection.connect(Connection.java:365)
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:524)
	... 5 more
Caused by: com.arm.debug.dtsl.nativelayer.NativeException: Device already has an active connection.
	at com.arm.debug.dtsl.components.Device.openConn(Device.java:403)
	at org.python.proxies.__main__$CTICore$6.super__openConn(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:441)
	at org.python.core.PyObject.__call__(PyObject.java:447)
	at org.python.pycode._pyx33.openConn$5(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\dtsl_config_script.py:77)
	at org.python.pycode._pyx33.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\dtsl_config_script.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
	at org.python.core.PyFunction.__call__(PyFunction.java:387)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220)
	at org.python.core.PyMethod.__call__(PyMethod.java:211)
	at org.python.core.PyMethod.__call__(PyMethod.java:201)
	at org.python.core.PyMethod.__call__(PyMethod.java:196)
	at org.python.core.PyObject._jcallexc(PyObject.java:3502)
	at org.python.proxies.__main__$CTICore$6.openConn(Unknown Source)
	at com.arm.debug.targetaccess.device.TargetDevice.doConnect(TargetDevice.java:513)
	... 8 more
Caused by: com.arm.rddi.RDDIException: Device already has an active connection.
	at com.arm.rddi.RDDI.checkResult(RDDI.java:1616)
	at com.arm.rddi.RDDI.access$1(RDDI.java:1603)
	at com.arm.rddi.RDDI$Debug.openConn(RDDI.java:231)
	at com.arm.debug.dtsl.components.Device.openConn(Device.java:401)
	... 30 more
Asynchronously called from thread MainThread
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.DebugService.createDebugService(DebugService.java:265)
	at com.arm.debugger.control.ConnectionController.manageDebugServiceAndInitialize(ConnectionController.java:757)
	at com.arm.debugger.control.ConnectionController.doInitialize(ConnectionController.java:559)
	at com.arm.debugger.control.ConnectionController.manageThreadModelAndInitialize(ConnectionController.java:539)
	at com.arm.debugger.control.ConnectionController.manageProgressResourceAndInitialize(ConnectionController.java:484)
	at com.arm.debugger.control.ConnectionController.initialize(ConnectionController.java:432)
	at com.arm.debugger.control.ConnectionManager.createConnection(ConnectionManager.java:360)
	at com.arm.debugger.launcher.TargetLauncher.launch(TargetLauncher.java:20)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-24 19:01:17.032
!MESSAGE Unable to connect to CPEN391_Config. Failed to connect to the device
Unable to connect to device Cortex-A9_0
Device already has an active connection.
!STACK 0
com.arm.debug.interpreter.ds.DSException: Failed to connect to the device
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:526)
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:513)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:295)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:1)
	at com.arm.debug.service.proxy.SingleThreader$QueuedCall.run(SingleThreader.java:61)
	at com.arm.debug.service.proxy.SingleThreader$1.run(SingleThreader.java:125)
Caused by: com.arm.debug.core.interfaces.connection.ConnectionException: Unable to connect to device Cortex-A9_0
	at com.arm.debug.targetaccess.device.TargetDevice.doConnect(TargetDevice.java:536)
	at com.arm.debug.targetaccess.device.TargetDevice.connect(TargetDevice.java:251)
	at com.arm.debug.core.engine.connection.Connection.connect(Connection.java:365)
	at com.arm.debug.interpreter.ds.DSInterpreter.initialise(DSInterpreter.java:524)
	... 5 more
Caused by: com.arm.debug.dtsl.nativelayer.NativeException: Device already has an active connection.
	at com.arm.debug.dtsl.components.Device.openConn(Device.java:403)
	at org.python.proxies.__main__$CTICore$6.super__openConn(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:441)
	at org.python.core.PyObject.__call__(PyObject.java:447)
	at org.python.pycode._pyx33.openConn$5(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\dtsl_config_script.py:77)
	at org.python.pycode._pyx33.call_function(C:\altera\15.0\embedded\ds-5\sw\debugger\configdb\Boards\Altera\Cyclone V SoC (Dual Core)\dtsl_config_script.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:301)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:194)
	at org.python.core.PyFunction.__call__(PyFunction.java:387)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:220)
	at org.python.core.PyMethod.__call__(PyMethod.java:211)
	at org.python.core.PyMethod.__call__(PyMethod.java:201)
	at org.python.core.PyMethod.__call__(PyMethod.java:196)
	at org.python.core.PyObject._jcallexc(PyObject.java:3502)
	at org.python.proxies.__main__$CTICore$6.openConn(Unknown Source)
	at com.arm.debug.targetaccess.device.TargetDevice.doConnect(TargetDevice.java:513)
	... 8 more
Caused by: com.arm.rddi.RDDIException: Device already has an active connection.
	at com.arm.rddi.RDDI.checkResult(RDDI.java:1616)
	at com.arm.rddi.RDDI.access$1(RDDI.java:1603)
	at com.arm.rddi.RDDI$Debug.openConn(RDDI.java:231)
	at com.arm.debug.dtsl.components.Device.openConn(Device.java:401)
	... 30 more
Asynchronously called from thread MainThread
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.DebugService.createDebugService(DebugService.java:265)
	at com.arm.debugger.control.ConnectionController.manageDebugServiceAndInitialize(ConnectionController.java:757)
	at com.arm.debugger.control.ConnectionController.doInitialize(ConnectionController.java:559)
	at com.arm.debugger.control.ConnectionController.manageThreadModelAndInitialize(ConnectionController.java:539)
	at com.arm.debugger.control.ConnectionController.manageProgressResourceAndInitialize(ConnectionController.java:484)
	at com.arm.debugger.control.ConnectionController.initialize(ConnectionController.java:432)
	at com.arm.debugger.control.ConnectionManager.createConnection(ConnectionManager.java:360)
	at com.arm.debugger.launcher.TargetLauncher.launch(TargetLauncher.java:20)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.launch(VariableResolvingLaunchConfiguration.java:273)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.arm.debugger.ux 4 0 2021-03-24 19:02:45.137
!MESSAGE Unable to connect to CPEN391_Config. The target hardware identity could not be verified. Please check that the target being connected to is of type Cyclone V SoC (Dual Core) 
!STACK 0
com.arm.debug.core.interfaces.engine.DebugException: The target hardware identity could not be verified. Please check that the target being connected to is of type Cyclone V SoC (Dual Core) 
	at com.arm.debug.targetaccess.device.DTSLConnection.connect(DTSLConnection.java:86)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:284)
	at com.arm.debug.service.DebugService$2.run(DebugService.java:1)
	at com.arm.debug.service.proxy.SingleThreader$QueuedCall.run(SingleThreader.java:61)
	at com.arm.debug.service.proxy.SingleThreader$1.run(SingleThreader.java:125)
Asynchronously called from thread MainThread
	at com.arm.debug.service.proxy.SingleThreader.execute(SingleThreader.java:157)
	at com.arm.debug.service.DebugService.createDebugService(DebugService.java:265)
	at com.arm.debugger.control.ConnectionController.manageDebugServiceAndInitialize(ConnectionController.java:757)
	at com.arm.debugger.control.ConnectionController.doInitialize(ConnectionController.java:559)
	at com.arm.debugger.control.ConnectionController.manageThreadModelAndInitialize(ConnectionController.java:539)
	at com.arm.debugger.control.ConnectionController.manageProgressResourceAndInitialize(ConnectionController.java:484)
	at com.arm.debugger.control.ConnectionController.initialize(ConnectionController.java:432)
	at com.arm.debugger.control.ConnectionManager.createConnection(ConnectionManager.java:360)
	at com.arm.debugger.launcher.TargetLauncher.launch(TargetLauncher.java:20)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
	at com.arm.debugger.control.VariableResolvingLaunchConfiguration.launch(VariableResolvingLaunchConfiguration.java:273)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.jface 2 0 2021-03-24 19:02:59.565
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2021-03-24 19:02:59.565
!MESSAGE A conflict occurred for CTRL+SHIFT+F:
Binding(CTRL+SHIFT+F,
	ParameterizedCommand(Command(org.eclipse.cdt.ui.edit.text.c.format,Format,
		Format Source Code,
		Category(org.eclipse.cdt.ui.category.source,C/C++ Source,C/C++ Source Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7a3d2349,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.cdt.ui.cEditorScope,,,system)
Binding(CTRL+SHIFT+F,
	ParameterizedCommand(Command(com.arm.scatter.editor.format,format,
		,
		Category(org.eclipse.core.commands.categories.autogenerated,Uncategorized,Commands that were either auto-generated or have no category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@43d7cc51,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	com.arm.scatter.editor.key.format,,,system)
